# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'BigYuzuTool.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(432, 657)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet(u"")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.NightlyButton = QPushButton(self.centralwidget)
        self.NightlyButton.setObjectName(u"NightlyButton")
        self.NightlyButton.setGeometry(QRect(20, 120, 390, 40))
        sizePolicy.setHeightForWidth(self.NightlyButton.sizePolicy().hasHeightForWidth())
        self.NightlyButton.setSizePolicy(sizePolicy)
        font = QFont()
        font.setKerning(True)
        self.NightlyButton.setFont(font)
        self.NightlyButton.setAutoFillBackground(True)
        self.NightlyButton.setStyleSheet(u"")
        self.NightlyButton.setFlat(False)
        self.BetaButton = QPushButton(self.centralwidget)
        self.BetaButton.setObjectName(u"BetaButton")
        self.BetaButton.setGeometry(QRect(20, 170, 390, 40))
        sizePolicy.setHeightForWidth(self.BetaButton.sizePolicy().hasHeightForWidth())
        self.BetaButton.setSizePolicy(sizePolicy)
        self.BetaButton.setFont(font)
        self.BetaButton.setAutoFillBackground(True)
        self.BetaButton.setStyleSheet(u"")
        self.BetaButton.setFlat(False)
        self.WifiFixButton = QPushButton(self.centralwidget)
        self.WifiFixButton.setObjectName(u"WifiFixButton")
        self.WifiFixButton.setGeometry(QRect(20, 340, 390, 40))
        sizePolicy.setHeightForWidth(self.WifiFixButton.sizePolicy().hasHeightForWidth())
        self.WifiFixButton.setSizePolicy(sizePolicy)
        self.WifiFixButton.setFont(font)
        self.WifiFixButton.setAutoFillBackground(True)
        self.WifiFixButton.setStyleSheet(u"")
        self.WifiFixButton.setFlat(False)
        self.UninstallWifiButton = QPushButton(self.centralwidget)
        self.UninstallWifiButton.setObjectName(u"UninstallWifiButton")
        self.UninstallWifiButton.setGeometry(QRect(20, 390, 390, 40))
        sizePolicy.setHeightForWidth(self.UninstallWifiButton.sizePolicy().hasHeightForWidth())
        self.UninstallWifiButton.setSizePolicy(sizePolicy)
        self.UninstallWifiButton.setFont(font)
        self.UninstallWifiButton.setAutoFillBackground(True)
        self.UninstallWifiButton.setStyleSheet(u"")
        self.UninstallWifiButton.setFlat(False)
        self.FolderButton = QPushButton(self.centralwidget)
        self.FolderButton.setObjectName(u"FolderButton")
        self.FolderButton.setGeometry(QRect(20, 20, 390, 50))
        sizePolicy.setHeightForWidth(self.FolderButton.sizePolicy().hasHeightForWidth())
        self.FolderButton.setSizePolicy(sizePolicy)
        self.FolderButton.setFont(font)
        self.FolderButton.setAcceptDrops(True)
        self.FolderButton.setAutoFillBackground(True)
        self.FolderButton.setStyleSheet(u"")
        self.FolderButton.setFlat(False)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(60, 100, 310, 20))
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setAutoFillBackground(False)
        self.line.setStyleSheet(u"")
        self.line.setLineWidth(2)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.line_2 = QFrame(self.centralwidget)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setGeometry(QRect(60, 270, 310, 20))
        sizePolicy.setHeightForWidth(self.line_2.sizePolicy().hasHeightForWidth())
        self.line_2.setSizePolicy(sizePolicy)
        self.line_2.setAutoFillBackground(False)
        self.line_2.setStyleSheet(u"")
        self.line_2.setLineWidth(2)
        self.line_2.setFrameShape(QFrame.HLine)
        self.line_2.setFrameShadow(QFrame.Sunken)
        self.BetaPatch = QPushButton(self.centralwidget)
        self.BetaPatch.setObjectName(u"BetaPatch")
        self.BetaPatch.setGeometry(QRect(20, 520, 390, 40))
        sizePolicy.setHeightForWidth(self.BetaPatch.sizePolicy().hasHeightForWidth())
        self.BetaPatch.setSizePolicy(sizePolicy)
        self.BetaPatch.setFont(font)
        self.BetaPatch.setAutoFillBackground(True)
        self.BetaPatch.setStyleSheet(u"")
        self.BetaPatch.setFlat(False)
        self.NightlyPatch = QPushButton(self.centralwidget)
        self.NightlyPatch.setObjectName(u"NightlyPatch")
        self.NightlyPatch.setGeometry(QRect(20, 470, 390, 40))
        sizePolicy.setHeightForWidth(self.NightlyPatch.sizePolicy().hasHeightForWidth())
        self.NightlyPatch.setSizePolicy(sizePolicy)
        self.NightlyPatch.setFont(font)
        self.NightlyPatch.setAutoFillBackground(True)
        self.NightlyPatch.setStyleSheet(u"")
        self.NightlyPatch.setFlat(False)
        self.line_3 = QFrame(self.centralwidget)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(60, 440, 310, 20))
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setAutoFillBackground(False)
        self.line_3.setStyleSheet(u"")
        self.line_3.setLineWidth(2)
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)
        self.Legacy = QPushButton(self.centralwidget)
        self.Legacy.setObjectName(u"Legacy")
        self.Legacy.setGeometry(QRect(20, 220, 390, 40))
        sizePolicy.setHeightForWidth(self.Legacy.sizePolicy().hasHeightForWidth())
        self.Legacy.setSizePolicy(sizePolicy)
        self.Legacy.setFont(font)
        self.Legacy.setAutoFillBackground(True)
        self.Legacy.setStyleSheet(u"")
        self.Legacy.setFlat(False)
        self.Legacy_2 = QPushButton(self.centralwidget)
        self.Legacy_2.setObjectName(u"Legacy_2")
        self.Legacy_2.setGeometry(QRect(20, 290, 390, 40))
        sizePolicy.setHeightForWidth(self.Legacy_2.sizePolicy().hasHeightForWidth())
        self.Legacy_2.setSizePolicy(sizePolicy)
        self.Legacy_2.setFont(font)
        self.Legacy_2.setAutoFillBackground(True)
        self.Legacy_2.setStyleSheet(u"")
        self.Legacy_2.setFlat(False)
        self.HDRVersion = QLabel(self.centralwidget)
        self.HDRVersion.setObjectName(u"HDRVersion")
        self.HDRVersion.setGeometry(QRect(20, 80, 380, 20))
        sizePolicy.setHeightForWidth(self.HDRVersion.sizePolicy().hasHeightForWidth())
        self.HDRVersion.setSizePolicy(sizePolicy)
        self.HDRVersion.setAutoFillBackground(False)
        self.HDRVersion.setAlignment(Qt.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        QWidget.setTabOrder(self.FolderButton, self.NightlyButton)
        QWidget.setTabOrder(self.NightlyButton, self.BetaButton)
        QWidget.setTabOrder(self.BetaButton, self.Legacy)
        QWidget.setTabOrder(self.Legacy, self.Legacy_2)
        QWidget.setTabOrder(self.Legacy_2, self.WifiFixButton)
        QWidget.setTabOrder(self.WifiFixButton, self.UninstallWifiButton)
        QWidget.setTabOrder(self.UninstallWifiButton, self.NightlyPatch)
        QWidget.setTabOrder(self.NightlyPatch, self.BetaPatch)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.NightlyButton.setText(QCoreApplication.translate("MainWindow", u"Download Latest Nightly", None))
        self.BetaButton.setText(QCoreApplication.translate("MainWindow", u"Download Latest Beta", None))
        self.WifiFixButton.setText(QCoreApplication.translate("MainWindow", u"Install Wifi Fix", None))
        self.UninstallWifiButton.setText(QCoreApplication.translate("MainWindow", u"Uninstall Wifi Fix", None))
        self.FolderButton.setText(QCoreApplication.translate("MainWindow", u"Select Your yuzu/sdmc/ Folder", None))
        self.BetaPatch.setText(QCoreApplication.translate("MainWindow", u"Patch In Beta", None))
        self.NightlyPatch.setText(QCoreApplication.translate("MainWindow", u"Patch In Nightly", None))
        self.Legacy.setText(QCoreApplication.translate("MainWindow", u"Download Legacy Discovery", None))
        self.Legacy_2.setText(QCoreApplication.translate("MainWindow", u"Install Legacy Discovery", None))
        self.HDRVersion.setText(QCoreApplication.translate("MainWindow", u"Current HDR Version: NOT SELECTED", None))
    # retranslateUi

