# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\BigYuzuTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(434, 486)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.NightlyButton = QtWidgets.QPushButton(self.centralwidget)
        self.NightlyButton.setGeometry(QtCore.QRect(20, 120, 391, 41))
        self.NightlyButton.setObjectName("NightlyButton")
        self.BetaButton = QtWidgets.QPushButton(self.centralwidget)
        self.BetaButton.setGeometry(QtCore.QRect(20, 170, 391, 41))
        self.BetaButton.setObjectName("BetaButton")
        self.WifiFixButton = QtWidgets.QPushButton(self.centralwidget)
        self.WifiFixButton.setGeometry(QtCore.QRect(20, 280, 391, 41))
        self.WifiFixButton.setObjectName("WifiFixButton")
        self.UninstallWifiButton = QtWidgets.QPushButton(self.centralwidget)
        self.UninstallWifiButton.setGeometry(QtCore.QRect(20, 330, 391, 41))
        self.UninstallWifiButton.setObjectName("UninstallWifiButton")
        self.FolderButton = QtWidgets.QPushButton(self.centralwidget)
        self.FolderButton.setGeometry(QtCore.QRect(20, 30, 381, 51))
        self.FolderButton.setObjectName("FolderButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 90, 441, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 260, 441, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.BetaPatch = QtWidgets.QPushButton(self.centralwidget)
        self.BetaPatch.setGeometry(QtCore.QRect(20, 460, 391, 41))
        self.BetaPatch.setObjectName("BetaPatch")
        self.NightlyPatch = QtWidgets.QPushButton(self.centralwidget)
        self.NightlyPatch.setGeometry(QtCore.QRect(20, 410, 391, 41))
        self.NightlyPatch.setObjectName("NightlyPatch")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 380, 441, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.Legacy = QtWidgets.QPushButton(self.centralwidget)
        self.Legacy.setGeometry(QtCore.QRect(20, 220, 391, 41))
        self.Legacy.setObjectName("Legacy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.NightlyButton.setText(_translate("MainWindow", "Download Latest Nightly"))
        self.BetaButton.setText(_translate("MainWindow", "Download Latest Beta"))
        self.WifiFixButton.setText(_translate("MainWindow", "Install Wifi Fix"))
        self.UninstallWifiButton.setText(_translate("MainWindow", "Uninstall Wifi Fix"))
        self.FolderButton.setText(_translate("MainWindow", "Select Your Yuzu Folder"))
        self.BetaPatch.setText(_translate("MainWindow", "Patch In Beta"))
        self.NightlyPatch.setText(_translate("MainWindow", "Patch In Nightly"))
        self.Legacy.setText(_translate("MainWindow", "Download Legacy Discovery"))
